version: "3.7"

services:
  sample-prod:
    container_name: qlik-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "1337:80"
    environment:
      - REACT_APP_API_BASE_URI=awesome
