version: "3.7"

services:
  sample:
    container_name: qlik-serve
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URI=http://ambhorepranav1c.mylabserver.com/api
